### ISSUE TITLE
Reproducability, correctness, and uniformity of int_range

### ISSUE THREAD

**Issue by jmid** [c-cube/qcheck#100]
I noticed a couple of things about `int_range` - which boils down to the current implementation of`Gen.int_range`:
```ocaml
  let int_range a b =
    if b < a then invalid_arg "Gen.int_range";
    if a >= 0 || b <= 0 then (
      (* range smaller than max_int *)
      assert (b-a >= 0);
      fun st -> a + (int_bound (b-a) st)
    ) else (
      (* range potentially bigger than max_int: we split on 0 and
         choose the itv wrt to their size ratio *)
      fun st ->
      let f_a = float_of_int a in
      let ratio = (-.f_a) /. (float_of_int b -. f_a) in
      if Random.float 1. < ratio then - (int_bound (abs a) st)
      else int_bound b st
    )
```

1. The outer else-branch relies on `Random.float`, hence consecutive calls with the same seed will not necessarily give the same result:
   ```ocaml
   utop # Gen.generate1 ~rand:(Random.State.make [| 1 |]) (Gen.int_range (-10000) 5000);;
   - : int = 148
   utop # Gen.generate1 ~rand:(Random.State.make [| 1 |]) (Gen.int_range (-10000) 5000);;
   - : int = -1292
   utop # Gen.generate1 ~rand:(Random.State.make [| 1 |]) (Gen.int_range (-10000) 5000);;
   - : int = -1292
   utop # Gen.generate1 ~rand:(Random.State.make [| 1 |]) (Gen.int_range (-10000) 5000);;
   - : int = -1292
   utop # Gen.generate1 ~rand:(Random.State.make [| 1 |]) (Gen.int_range (-10000) 5000);;
   - : int = 148
   ```
   I consider such reproducability central to property-based testing: on the same seed it should generate the same output. The issue can easily be fixed by using `Random.State.float st` instead.

2. Our old friend `min_int` is numerically one larger in a 2-complement representation than `max_int` which can cause two problems.
   First: If the range is `[min_int; 0]` the range is actually `max_int+1` long causing the "positive branch" to fail the assertion: 
   ```ocaml
   utop # Gen.generate1 (Gen.int_range min_int 0);;
   Exception: Assert_failure ("src/core/QCheck.ml", 167, 6).
   ```
   Second: If the range crosses 0, we can end up calling `abs` with `a = min_int` which actually yields a negative number (`min_int` again!) causing the `int_bound` call to fail:
   ```ocaml
   utop # Gen.generate1 (Gen.int_range min_int 5);;
   Exception: Invalid_argument "Gen.int_bound".
   utop # Gen.generate1 (Gen.int_range (min_int+1) 5);;
   - : int = -2313078558937646613
   ```

3. I really appreciate the extension beyond `max_int` sized intervals, but I believe it breaks uniformity.
    Consider the following example computing of the distribution of 1 million `int`s from -10 to 10:
   ```ocaml
   open QCheck;;
   let t = Test.make ~count:1_000_000 (set_stats [("dist",fun i -> i)] (int_range (-10) 10)) (fun _ -> true);;
   QCheck_runner.run_tests ~verbose:true [t];;
   ```
   This reveals that 0 is included in both branches and hence twice as likely:
   ```
   stats dist:
     num: 1000000, avg: 0.00, stddev: 5.92, median 0, min -10, max 10
     -10: ###########################                                   45373
      -9: ###########################                                   45601
      -8: ###########################                                   45608
      -7: ###########################                                   45774
      -6: ###########################                                   45185
      -5: ###########################                                   45393
      -4: ###########################                                   45405
      -3: ###########################                                   45266
      -2: ###########################                                   45506
      -1: ###########################                                   45394
       0: #######################################################       90454
       1: ###########################                                   45855
       2: ###########################                                   45520
       3: ###########################                                   45643
       4: ###########################                                   45343
       5: ###########################                                   45259
       6: ###########################                                   45483
       7: ###########################                                   45175
       8: ###########################                                   45526
       9: ###########################                                   45467
      10: ###########################                                   45770
   ```
   In this case there are 20 + 1 = 21 integers to choose from as far as I can tell, hence we need to extend the size ratio of one side by 1 (the side that includes zero) and exclude it from the other. A patch along these lines reads like this:
   ```ocaml
   let int_range a b =
       if b < a then invalid_arg "Gen.int_range";
       if a >= 0 || b < 0 then (
         (* range smaller than max_int *)
         assert (b-a >= 0);
         fun st -> a + (Gen.int_bound (b-a) st)
       ) else (
         (* range potentially bigger than max_int: we split on 0 and
            choose the itv wrt to their size ratio *)
         fun st ->
         let f_a = float_of_int a in
         let ratio = (-.f_a) /. (1. +. float_of_int b -. f_a) in
      if Random.State.float st 1. <= ratio then - (Gen.int_bound (abs (a+1)) st) - 1
         else Gen.int_bound b st
       )
   ```
   The idea here is to maintain a split in two: `[a;-1] [0;b]` when the bounds are on either side of 0.
   In the last `then` branch we know `a < 0` hence it is safe to add 1. For the `[min_int; 5]` example, it means we generate a number in the lower half `[min_int; -1]` by generating one in `[0; max_int]`, switching signs and subtracting 1 (thus avoiding overflow). I also changed the ratio comparison to `<=` which is unlikely to ever get hit, but strictly part of the `[a;-1]` ratio range in my understanding. Finally by changing the initial test from `b <= 0` to `b < 0` we fix the first `min_int` issue (from point 2. above).
   I've tested this briefly on a bunch of boundary cases 
   ```
   let t = Test.make ~count:1_000_000 (set_stats [("dist",fun i -> i)] (make (int_range (-10) 10))) (fun _ -> true);;
   let t = Test.make ~count:1_000_000 (set_stats [("dist",fun i -> i)] (make (int_range (-1) 10))) (fun _ -> true);;
   let t = Test.make ~count:1_000_000 (set_stats [("dist",fun i -> i)] (make (int_range (-1) 1))) (fun _ -> true);;
   let t = Test.make ~count:1_000_000 (set_stats [("dist",fun i -> i)] (make (int_range (-1) 0))) (fun _ -> true);;
   let t = Test.make ~count:1_000_000 (set_stats [("dist",fun i -> i)] (make (int_range (min_int) (0)))) (fun _ -> true);;
   let t = Test.make ~count:1_000_000 (set_stats [("dist",fun i -> i)] (make (int_range (min_int) (1)))) (fun _ -> true);;
   let t = Test.make ~count:1_000_000 (set_stats [("dist",fun i -> i)] (make (int_range (min_int) (5)))) (fun _ -> true);;
   ```
   and it seems to fix the distribution and the mentioned issues, but I would appreciate a couple of extra eyes @ghilesZ @c-cube 🙂

**Comment by ghilesZ** [comment]
@jmid This is very clever and looks correct to me, well played. To be picky, in the last then branch, for the same reason i think it is best to do ````(- (a+1))```` instead of  ````(abs (a+1))````, which avoids the test performed by ```abs```.
Also, i was wondering, could the same trick (split on 0) be applied to ````float_range```` ?

**Comment by jmid** [comment]
> Also, i was wondering, could the same trick (split on 0) be applied to `float_range` ?

That's quite plausible... 🤔 The only reason I came across `int_range` was that some older generator using it failed when I reran it. I'm not sure I've ever used `float_range` myself 🤷‍♂️

**Comment by c-cube** [comment]
1) was definitely a mistake I should have seen in a review, good catch. For the rest, that looks excellent, thanks for the report and fix. I'm not sure about `float_range` either.
