### ISSUE TITLE
Documentation contains NEXT_RELEASE

### ISSUE THREAD

**Issue by Chris00** [c-cube/qcheck#11]
The documentation contains comments such as 
```ocaml
  (** @since NEXT_RELEASE *)
```
I believe that `NEXT_RELEASE` should be substituted by a version number.

**Comment by c-cube** [comment]
Which documentation? The `dev` one, yes. Otherwise it's normal, I only substitute those strings before the release :-)

**Comment by Chris00** [comment]
The one that is installed by OPAM.

**Comment by c-cube** [comment]
My bad then. I'll make a new release.

**Comment by Chris00** [comment]
OK—thanks.

**Comment by c-cube** [comment]
https://github.com/ocaml/opam-repository/pull/8233

**Comment by Chris00** [comment]
While you are at it, the doc also says
```
  - generate 20 random trees using {! Arbitrary.fix} :
```
but there is no more an `Arbitrary` submodule.

**Comment by c-cube** [comment]
Fixed.

**Comment by Chris00** [comment]
Sorry to bother  but `QCheck.Test.run_exn test` should be replaced by `QCheck.Test.check_exn test`.
