### ISSUE TITLE
Followup: Reimplement function shrinking in integrated shrinking

### ISSUE THREAD

**Issue by Sir4ur0n** [c-cube/qcheck#110]
See discussion https://github.com/c-cube/qcheck/pull/109#discussion_r612473670

**Comment by c-cube** [comment]
I have another (tentative) idea.

Each type is a set, and so far we have generators which randomly sample points in this set (individual elements). For functions we don't really want to sample points to compare to; I think instead we want to randomly choose predicates that divide the set in 2 subsets of various shapes and sizes (not just a singleton and the rest).

So for each type that we support as function parameter, we need a collection of predicates and the function itself is a decision tree whose leaves are values. Shrinking a decision tree is trivial. Examples of predicates:

```ocaml
type 'a predicate = 'a -> bool

type ('a, 'b) decision_tree =
  | Return of 'b (* use normal gen here *)
  | Decide of 'a predicate * ('a,'b) decision_tree * ('a,'b) decision_tree

module Int = struct
  let lt x : int predicate = fun y -> y < x
  let gt x : int predicate = fun y -> y > x
  let even : int predicate = fun x -> x mod 2 = 0
end

module String = struct
  let len (p:int predicate) : string predicate =  fun s -> p (String.length s)
  let for_all (p:char predicate) : string predicate = fun s -> String.for_all p s
end

(* etc. *)

let rec eval_dt (dt: ('a,'b) decision_tree) (st:RS.t) (x:'a) : 'b =
  match dt with
  | Return g -> g st
  | Decide (p, left, right) -> if p x then eval_dt left st x else eval_dt right st x

type ('a,'b) fun_gen = Fun  ('a,'b) decision_tree 

let fun_int (g:'b gen) : (int -> 'b) gen =
  let pred = oneofl [
   small_nat >|= Int.gt;
   (-1_000_000--1_000_000) >|= Int.lt; 
   even; 
  ] in
  fix (fun self ->
     frequencyl [ 3, pure (Return g); 1, (fun p l r -> Decide (p,l,r)) <$> pred <*> self <*> self])
```

**Comment by c-cube** [comment]
Actually these random predicates could even take a subset of values as a parameter.

For integers for example, it starts with `[min_int, max_int]` and can pick a pivot to compare to, within that range. But then, one we decide on `fun x -> x < pivot`, we can generate the left and right sub-trees in the `[min_int, pivot[` and `[pivot, max_int]` ranges, and recursively.

That also means that shrinking should be done from the leaves up, so that this nice property of non-redundancy of tests can be preserved.

**Comment by Sir4ur0n** [comment]
I believe this issue can be closed as actually, I adapted the function shrinking code in QCheck2
