### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by sir4ur0n** [c-cube/qcheck#111]
Ironically there aren't tests for QCheck, which makes it uncomfortable/non-trivial to test the features (mainly, generators and shrinkers).

This could be both unit tests (e.g. "Shrinking 100 towards 0 gives 0, 50, 75, etc.") and PBTs (e.g. "`int_range a b` only gives values between `a` and `b`").

This would also help reproducing bugs in QCheck issues

**Comment by c-cube** [comment]
Yep :sweat_smile: . That'd be useful.

**Comment by jmid** [comment]
Closing as we now have a collection of expect tests and unit tests, e.g., from #234 and #237
