### ISSUE TITLE
Option generator

### ISSUE THREAD

**Issue by vch9** [c-cube/qcheck#117]
I'm sorry If that question has already been asked.

Is there a particular reason `Gen.opt` produces 15% of `None` ?

Could we (or I):
* Add comments about that choice
* Handle % of `None` as function optional parameter

**Comment by c-cube** [comment]
Yes to both! 15% was done because it seems to me that `Some x` is more interesting than `None`, so you want it more frequently; the exact number is, well, just a guess. That said, an optional parameter (or alternative generator with an explicit fraction) would be very welcome.
