### ISSUE TITLE
Remove `arbitrary` and use `Gen.t` directly in tests

### ISSUE THREAD

**Issue by Sir4ur0n** [c-cube/qcheck#119]
Copy-pasting and shaving off [my comment in QCheck2 MR](https://github.com/c-cube/qcheck/pull/109#issuecomment-828611466):

-----------------------------------------------

Does it still make sense to keep `arbitrary` (note: Once QCheck2 is merged)? I feel like we would be just as happy with only `Gen.t` (no matter if we keep it here, or if `arbitrary` becomes `Gen.t`).

On top of `Gen.t`, `arbitrary` has:
* pretty printing
* stats
* collect

As @jmid interestingly [pointed out](https://github.com/c-cube/qcheck/pull/109#pullrequestreview-635419995), both stats and tag collection could be moved out as their usage is a bit clunky. Maybe some kind of wrapper so that most users don't even see them, and those who do only wrap in the few places they are interested in stats.

Which leaves us with the pretty printer.

My gut feeling is: we could put the pretty printer in `Gen.t` (as long as it remains optional) and add a `val with_printer : printer -> 'a Gen.t -> 'a Gen.t` function.

The documented pattern, and probably the most used one, would be `|> with_printer foo_printer`:
```ocaml
let foo_gen : foo Gen.t = 
  a_gen >>= fun a ->
  b_gen >>= fun b ->
  make_foo a b
  |> with_printer Foo.pp
```

Pros:
* users now only manipulate one main QCheck type, which is a big UX and verbosity win
* users usually want to combine generators, and pass the pretty printer at the end (just before passing a generator to a test). Intermediary generators only used for composition don't need a pretty printer
* Take the opportunity of this breaking change to fix some deprecations, errors/mistakes (like `ui32`), make the API consistent

Cons:
* This is undoubtedly a breaking change, and a big one :see_no_evil: 
* Needs significant work

Would that be a QCheck3? What is the versioning strategy if we go the way of a full breaking change?

The more I write QCheck code, the more this juggling between `Gen.t` and `arbitrary` is off-putting (and hard to understand its need as a user, as anyway print/collect/stats are optional)

Note: It may be wise to do https://github.com/c-cube/qcheck/issues/107 together with this issue, as this would be highly conflictual and/or involve a lot of throw-away code to do either one first

**Comment by c-cube** [comment]
Maybe it's simpler if the test function takes a generator, a printer, and the property, rather than bundling printer and generator together just before? In  general you might write a bunch of different generators for a type, but only one printer. For the statistics it holds as well I htink (except with an optional argument).

**Comment by Sir4ur0n** [comment]
It is an alternative indeed. However what is nice with packaging it inside `Gen.t` is that for some functions we can handle a printer in best-effort, lowering further the work for users.

E.g. `pair g1 g2` would have a printer without any work if both `g1` and `g2` have a printer (actually as soon as 1 has a printer, we can actually have a printer, by printing a placeholder like `<no printer>` for the other element.

This also applies to some other functions like `choose`

**Comment by Sir4ur0n** [comment]
Well typically the printer could **not** be carried along `map`, `ap` or `bind` as the type can freely change. I think this "carrying along" would only work on the subset of functions that take a `'a Gen.t` in argument, and return a `'b Gen.t` where `'b` is either `'a` or a "visible" part of `'a` (vague hand-waving intensifies :grin: ) like tuples

**Comment by c-cube** [comment]
Yeah I think it's not worth it :slightly_smiling_face: . Better suggest people to use ppx_deriving, and actually support `Format` instead of just `to_string` (or rather support both?)

**Comment by Sir4ur0n** [comment]
The more I think about it the more convinced I am by your proposal: `Test.make` should take a generator, a law (`'a -> bool`), and **optionally** a printer, a stats function, a collect function. `Gen.t` should only take care of the generation (+ shrinking) part (separation of concerns).

Of course this doesn't mean we should let users do all the work: I guess we could recycle the `Print` module to provide various utils to make it simpler to compose printers, a la `pair/contramap/etc`.

A test could thus write:
```ocaml
Test.make
  ~pp:Print.(pair Foo.pp Bar.pp)
  ~collect:...
  ~stats:...
  Gen.(pair foo_gen bar_gen)
  @@ fun (foo, bar) -> ...
```

**Comment by c-cube** [comment]
Cool! I think also we could have both `print` that takes `'a -> string`, and `pp` that is a formatter function, as derived from `ppx_deriving.show`; both being optional.

**Comment by vch9** [comment]
I am giving it a shot, I'll let your know if I get something (quiet) good !

**Comment by Sir4ur0n** [comment]
What about backward compatibility @c-cube ? I reckon this would be a major breaking change, and I have doubts we can keep backward compatibility

Of course we can have an alias `type arbitrary = Gen.t` but still, a lot of code won't compile anymore

**Comment by c-cube** [comment]
I think removing arbitrary in qcheck2 is fine; for qcheck1 I think it can all be transferred in the test conversion.

a qcheck1 test packs a property and a 'a arbitrary; deconstruct the arbitrary and use the components (and property) to build a qcheck2 test. Does that work?

**Comment by vch9** [comment]
I'll go for a full remove in QCheck2 for now, but I believe it is doable for QCheck1 (but it will take some time)

**Comment by c-cube** [comment]
You mean, doable to not break compatibility at all, right? :)

**Comment by vch9** [comment]
Yes, as you said we can deconstruct the arbitrary and use the components to product a qcheck2 test. I'll try to produce a WIP merge request so you can follow the choices I've made :)

**Comment by c-cube** [comment]
awesome, thank you!

**Comment by vch9** [comment]
Would it be a good idea to remove the module `Gen` and simply inline the function in `QCheck2.ml` ?
Just like `arbitrary` and one could write
```ocaml
let test =
  QCheck2.(Test.make
    ~name:"test"
    int
    (fun x -> x > 0)

(* instead of *)
let test =
  QCheck2.(Test.make
    ~name:"test"
    Gen.int
    (fun x -> x > 0)

```

**Comment by c-cube** [comment]
Good question. It's more fluent, but it tends to pollute a bit the namespace. More opinions would be welcome :)

**Comment by vch9** [comment]
It won't pollute more than it is already since generators will replace arbitrary. But that's an opportunity to pollute less than before.

**Comment by Sir4ur0n** [comment]
My 2 cents: I fully agree with @vch9 : as it will replace the current `arbitrary` functions/values, I don't think there will be much more pollution, but it will be more convenient and a tad less verbose

**Comment by c-cube** [comment]
@Sir4ur0n alright, I think we all agree now. It's in progress on #131 :)
