### ISSUE TITLE
Choose/Oneof: shrink towards the first or not

### ISSUE THREAD

**Issue by Sir4ur0n** [c-cube/qcheck#121]
Followup of [this discussion](https://github.com/c-cube/qcheck/pull/109#discussion_r625461765)

@c-cube asked if we really want to shrink towards the first element of a list of values/generators (`choose` and `oneof` families of functions).

IMHO it's best to shrink towards the first element of the list:
* consistency: no matter the starting point (root generated value), the "optimal" shrink will always be the same
* it doesn't hurt either, even if no branch is smaller than another, to always pick one

We can also provide an optional parameter to decide the strategy: first element, or none (only shrink on the selected one)

Discuss :grin:

**Comment by c-cube** [comment]
I think it's fine to shrink towards the beginning of the list, if it's clearly documented :-). It's a good ability to have, I think I was just surprised by it initially.

**Comment by c-cube** [comment]
I think other discussions on #116 and previous have converged to a point where this is indeed the better behavior.
