### ISSUE TITLE
ppx_deriving_qcheck

### ISSUE THREAD

**Issue by vch9** [c-cube/qcheck#127]
Hello !

I just want to let you know that I'm currently working on a ppx for qcheck.
My main focus is to produce a `t arbitrary` for (any?) `t`. 

Here's the project:
https://github.com/vch9/ppx_deriving_qcheck

There is no release yet, but feel free to take a look if you're curious.
Especially in the tests, you'll be able to see what the generated code
looks like.

**Comment by c-cube** [comment]
Awesome! I'll take a look :)
I've thought about something like that for a long time but never followed through.

**Comment by c-cube** [comment]
I think it'd be nice to name it `[@@deriving qcheck]`, no? it'd be more explicit…

**Comment by vch9** [comment]
`[@@deriving arb]` might no be the most explicit name, but wouldn't `[@@deriving qcheck]` be to general ?

**Comment by c-cube** [comment]
too general in what sense? I don't see with what it could be confused.

**Comment by vch9** [comment]
I don't really know the conventions about a deriving name. It's true that the ppx, I believe, will not derive anything else ?
That might be too much but we could maybe have 2 rules:
```
type t = A | B | C [@@deriving qcheck]
```
who would generate a `QCheck.arbitrary`

and
```
type t = A | B | C [@@deriving generator]
```
who would create a `unit -> t` generator, abstracting the QCheck library.

**Comment by vch9** [comment]
How would you feel about adding ppx_deriving_qcheck into qcheck ? I'm currently cleaning and improving the code right now.

This would avoid to avoid a dependency from qcheck **and** ppx_deriving_qcheck.  Beside the advantages of a deriver, the "exhibition" given to the deriver would avoid people to work on a similar tool.

**Comment by c-cube** [comment]
> How would you feel about adding ppx_deriving_qcheck into qcheck? I'm currently cleaning and improving the code right now.

that sounds like a good idea.

> This would avoid to avoid a dependency from qcheck **and** ppx_deriving_qcheck.

I don't see how, a ppx deriver would still be its own package. It makes sense for it to live in the same repo, but not to be the same package.

**Comment by vch9** [comment]
> I don't see how, a ppx deriver would still be its own package. It makes sense for it to live in the same repo, but not to be the same package.

Yep right my bad, we would still have both packages.

Well, I'll be soon creating a MR about the package.
