### ISSUE TITLE
Support a global QCHECK_COUNT configuration

### ISSUE THREAD

**Issue by Sir4ur0n** [c-cube/qcheck#137]
Currently the number of test runs per property (via `~count`, default `100`) is not configurable globally (or I did not find such a feature and it's not documented :grin: ).

What do you think about supporting such a global flag to be able to run all QCheck tests with a different `count`?

The question is about priority: if a test explicitly uses `~count:42` and `QCHECK_COUNT` is set to 1000, what value should we use? I would sligthly prefer: `explicit ~count` > `QCHECK_COUNT` > `default 100` but I think I would find `QCHECK_COUNT` > `explicit ~count` > `default 100` fine too

**Comment by c-cube** [comment]
we could have a global ref for the default value (initally set to `100` unless `QCHECK_COUNT` env var is set).

- `explicit ~count > QCHECK_COUNT > default 100` is fine
- `QCHECK_COUNT > explicit ~count > default 100` is absolutely not fine. If I specify `~count` it should always be enforced! (think of very heavy tests).

**Comment by vch9** [comment]
>     * `QCHECK_COUNT > explicit ~count > default 100` is absolutely not fine. If I specify `~count` it should always be enforced! (think of very heavy tests).

I agree with you, `explicit ~count` should always be the priority.
