### ISSUE TITLE
Negative count in Test.make

### ISSUE THREAD

**Issue by vch9** [c-cube/qcheck#141]
I am currently solving #137  While writing test I just found out that a negative count is allowed ? It does end up having a strange behavior:
![image](https://user-images.githubusercontent.com/32700018/125418923-ac558769-ef93-42d6-9a42-28bdaa18fb3e.png)

**Comment by c-cube** [comment]
it's allowed only because no one checked for it, but obviously it's a stupid bug :). A one line `if count <= 0 then invalid_arg "…"` is enough.

but kind of stupid
