### ISSUE TITLE
`Gen.string_readable` can produce unreadable strings - misnamed?

### ISSUE THREAD

**Issue by jmid** [c-cube/qcheck#155]
While testing `QCheck2` for PR #153 I realized that both `QCheck2.Gen.string_readable` and  `QCheck.Gen.string_readable` produce strings with the `Gen.char` generator - hence in the range 0-255. 

With the name `string_readable` as a first-time user, I had expected the generator to use `Gen.printable` as its underlying character generator - although I was also puzzled by the difference in the readable/printable terminology.

```ocaml
utop # QCheck.Gen.(generate1 string_readable);;
- : striÒ" = " ajRª;
utop # QCheck.Gen.(generate1 string_r\016yº\002~&dûWÛwí¤h>ÄÌI¯O6\022í4v"
utop # QCheck2.Gen.(generate1 string_readable);;
utop # QCheck2.Gen.(generate1 string_readable);;
- : string = "d¬C¤y3)\015"
utop # QCheck2.Gen.(generate1 string_readable);;
- : string = "¾\015ç"
```
Above, the two samples from `QCheck.Gen.string_readable` and the first sample from `QCheck2.Gen.string_readable` produced strings with suitable control characters (backspace, clear?) to mess up the `utop` output - bonus points to `QCheck2` for deleting the sample entirely!

**Comment by jmid** [comment]
BTW: `Gen.string_readable` was added to address issue #75.

**Comment by c-cube** [comment]
My bad, I was the origin of the bad name. I just fixed it by deprecating the `string_readable` in favor of the new `string_printable`, and both use `Gen.printable` to pick chars.

**Comment by jmid** [comment]
I think there are two orthogonal issues here: (a) the generator's name and (b) the generator's functionality. We agree there was a mismatch between the two.

The proposed fix in 727dcc5 
- adds a new generator `Gen.string_printable` where the two are better aligned  😀
- deprecates `Gen.string_readable` 

`Gen.string_readable` was added to address issue #75 as an alias of `Gen.string` but without an optional parameter (which was causing problems type-wise). As far as I can tell `Gen.string_printable` does not fill the hole that  `Gen.string_readable`'s functionality was intended to fill ("string generator w/char codes in 0-255 like `Gen.string`, but without an optional parameter"):
```ocaml
  let string_readable = string_printable
```
With this definition, after an upgrade any users of `Gen.string_readable` (@yawaramin ?) will test only a subset of the strings that they previously did. Shouldn't we point users to `Gen.(string_of char)` instead? (But then we might as well just use `Gen.(string_of printable)` and omit `Gen.string_printable`...   🙃)

Semi-seriously: the fewer combinators we have, the better. We are already short on tests for the ones we have despite my efforts in PR #153. `QCheck2` may be a good reason to make a clean generator redesign as you suggested in https://github.com/c-cube/qcheck/issues/75#issuecomment-534181180. Starting with strings, asking for an explicit `char` generator argument to `Gen.string_of` looks pretty clean to me: `Gen.(string_of char)`, `Gen.(string_of printable)`, `Gen.(string_of numeral)`, ...
As an added bonus, with suitable char generator names (`Gen.(printable, numeral, latin1, ascii, ...)`), this will force users to document in their tests what kind of strings they want to test a property with.

Getting back to the `Gen.string_readable` issue:
Whatever we decide on we should do the same for `QCheck2.Gen` which has the same mismatch, so that they remain relatively in sync. The proposed fix in 727dcc5 only makes changes to `QCheck`.

**Comment by c-cube** [comment]
i don't think QChech2 needs to have the exact same combinators, it can be more orthogonal :-).
I can revert the alias and still deprecate `string_readable` since it's mis-named. `string_printable` is useful on its own.

**Comment by jmid** [comment]
I agree:
- `QCheck` and `QCheck2` don't need to have the exact same combinators 
  (and I think @sir4ur0n has done a good job trying to unify the `Gen.t` and `arbitrary` interfaces)
- Yes, `QCheck.Gen.string_printable` could be useful on its own.
  (that is also an argument for adding it to `QCheck2.Gen`, no? 😉)
- Deprecating `QCheck.Gen.string_readable` sounds reasonable.
  Since `QCheck2.Gen.string_readable` can still produce unreadable strings
  it should probably just be deleted from the `QCheck2.Gen` interface?

**Comment by c-cube** [comment]
- yes
- yes
- yes

:woman_dancing:

**Comment by sir4ur0n** [comment]
@vch9 is the one who has removed `arbitrary`, not me :sweat_smile:

**Comment by jmid** [comment]
I've just created PR #158 to bring QCheck2 up to speed with the proposed change.
