### ISSUE TITLE
generate1 and generate in module Gen are broken

### ISSUE THREAD

**Issue by vch9** [c-cube/qcheck#185]
```ocaml
let rand = Random.State.make [| 42 |]

let () =
  let x = QCheck.Gen.small_int rand in
  assert (x = QCheck.Gen.generate1 ~rand QCheck.Gen.small_int)
```

This fails because `generate1` and `generate` has an optional value for `~rand`:
```ocaml
let generate ?(rand=Random.State.make_self_init())
```
The `make_self_init` (I believe) modifies the internal state of `Random.State`

**Comment by jmid** [comment]
I think this is just the design of `Random.State.t` showing -- it has internal state:
```ocaml
utop # let rand = Random.State.make [| 42 |];;
val rand : Random.State.t = <abstr>
utop # Random.State.int;;
- : Random.State.t -> int -> int = <fun>
utop # Random.State.int rand 10;;
- : int = 4
utop # Random.State.int rand 10;;
- : int = 5
```

Here's the beginning of `random.ml`:
```ocaml
module State = struct

  type t = { st : int array; mutable idx : int }
  ...
```


As long as you start `Gen.generate1` in the same `Random.State.t` with the *same internal state* things work as expected:
```ocaml
utop # QCheck.Gen.(generate1 ~rand:(Random.State.make [| 42 |]) nat, generate1 ~rand:(Random.State.make [| 42 |]) nat);;
- : int * int = (623, 623)
```

**Comment by vch9** [comment]
Well yes this is my bad. I made the confusion between `Random.State` and the seed. My assumption of `make_self_init ()` is wrong; closing this.

**Comment by jmid** [comment]
> I made the confusion between `Random.State` and the seed. 

The relation between `QCheck_runner.run_tests`'s `~seed` parameter - and (in my case) `Test.check_exn`'s `~rand` parameter has also confused me in the past. Looking at the API again one can apparently do:
```ocaml
  set_seed my_seed; 
  random_state ()
```
to get the `Random.State.t` corresponding to `my_seed`. I didn't realize this before though.
It could be cleaner if it wasn't side-effecting the runner's internal state though... 🤷‍♂️
