### ISSUE TITLE
Deriver: support qcheck and qcheck2

### ISSUE THREAD

**Issue by vch9** [c-cube/qcheck#190]
The deriver should create QCheck and QCheck2 generators.
The choice could be given in the deriver's plugin name: `[@@deriving qcheck]` and `[@@deriving qcheck2]`.

**Comment by c-cube** [comment]
Would it make sense for `[@@deriving qcheck]` to also produce an arbitrary object in addition to gen + shrinker? The suffix versions would be used to derive only specific components.
