### ISSUE TITLE
Deriver: first release

### ISSUE THREAD

**Issue by vch9** [c-cube/qcheck#192]
I have opened several issues that I believe should be fixed before we release the deriver.

- [ ] #191
- [ ] #190 
- [ ] #189
- [x] #188 
- [x] #187

Feel free to add if I missed something :)

**Comment by vch9** [comment]
I'd propose to not require #191 for the first release. I currently have the time to solve multiple issues in that list, but, unfortunately I don't think I can right now do #191. However, I think this should not be blocking for a first release, shrinkers are great yes, and we will derive them as well, but generators would be a great first feature.

What do you think @jmid @c-cube

**Comment by jmid** [comment]
As I wrote elsewhere I think only #188 is required before a release (from my POV)

**Comment by vch9** [comment]
> As I wrote elsewhere I think only #188 is required before a release (from my POV)

Required yes maybe. It will work for QCheck2, but it's a bit unfortunate to restrict the deriver to the new version only I think

**Comment by maurobringolf** [comment]
Any updates on this? Is there something a new contributor could help with?

So far I am a happy user of `qcheck` (thanks!) and recently ran into https://github.com/c-cube/qcheck/issues/197 and would very much like to see this merged. I am not (yet) familiar with the codebase, but am willing to invest time and help move this forward.

**Comment by vch9** [comment]
> Any updates on this? Is there something a new contributor could help with?
> 
> So far I am a happy user of `qcheck` (thanks!) and recently ran into #197 and would very much like to see this merged. I am not (yet) familiar with the codebase, but am willing to invest time and help move this forward.

We should not be far away from a first release. There is two open merge request regarding the deriver:
1. https://github.com/c-cube/qcheck/pull/215: fix a minor bug
2. https://github.com/c-cube/qcheck/pull/209: support qcheck and qcheck2

The first one should be closed pretty easily, once @jmid and I agree on the patch. The second one however contains a lot of boiler-plate code. Reviews/tests/inputs would be more than welcome to help the maintainers in a potential merge.

**Comment by jmid** [comment]
Closing as we already had a first release of `ppx_deriving_qcheck`
