### ISSUE TITLE
Error: `Ppxlib.Deriving: 'qcheck' is not a supported type deriving generator`

### ISSUE THREAD

**Issue by tomsib2001** [c-cube/qcheck#197]
Hi, I have an issue when using `[@@ deriving qcheck]` in OCaml 4.12.0 and `ppx_deriving_qcheck 0.1.0` (Ubuntu `20.04.3`).

Here's a minimal example:

`quickcheck_minimal_bug.ml`:
```ocaml
type toto = A of int | B of bool [@@deriving qcheck]
```
`dune`:
```ocaml
(executable
(name qcheck_minimal_bug)
(modules qcheck_minimal_bug)
(libraries qcheck)
(preprocess (pps ppx_deriving_qcheck))
)
```

When running `dune build`, I get:
```shell
dune build
File "qcheck_minimal_bug.ml", line 1, characters 45-51:
1 | type toto = A of int | B of bool [@@deriving qcheck]
                                                 ^^^^^^
Error: Ppxlib.Deriving: 'qcheck' is not a supported type deriving generator
```

Here is everything installed related to qcheck:
```ocaml
opam search qcheck
# Packages matching: match(*qcheck*)
# Name              # Installed # Synopsis
alg_structs_qcheck  --          Provides qCheck generators for laws of alg_structs
ppx_deriving_qcheck 0.1.0       PPX Deriver for qcheck
qcheck              0.18        Compatibility package for qcheck
qcheck-alcotest     --          Alcotest backend for qcheck
qcheck-core         0.18        Core qcheck library
qcheck-ounit        0.18        OUnit backend for qcheck
qcstm               --          A simple state-machine framework for OCaml based on QCheck
qtest               --          qtest : Inline (Unit) Tests for OCaml.
```

Thanks in advance for your kind assistance.

**Comment by jmid** [comment]
Thanks for your report. As far as I can see, `ppx_deriving_qcheck 0.1.0` listed on opam is from Valentin's previous (now archived) repo: https://github.com/vch9/ppx_deriving_qcheck
There has been a number of changes to the deriver since the move here, but there has been no official release since (an issue is tracking it: #192) 

A couple of questions to help resolve the issue:
- Do you get the same behaviour with the deriver included in the qcheck repo?
- Which version of Ppxlib are you using? (0.23 had a number of changes AFAIK)

**Comment by tomsib2001** [comment]
Hi, Thanks for your answer!
If I pin the `master` branch to opam, `dune build` succeeds. My version of `ppxlib` is `0.23`.
Should `merlin` know a value `gen_toto` or `toto : arbitrary` after the above definition?

**Comment by vch9** [comment]
> Should `merlin` know a value `gen_toto` or `toto : arbitrary` after the above definition?

Yes it should! It is currently hidden but I will change this :) Also be aware the current deriver produces `'a QCheck.Gen.t` and not `'a arbitrary`, this should be fixed in https://github.com/c-cube/qcheck/issues/190

**Comment by vch9** [comment]
> Thanks for your report. As far as I can see, `ppx_deriving_qcheck 0.1.0` listed on opam is from Valentin's previous (now archived) repo: https://github.com/vch9/ppx_deriving_qcheck There has been a number of changes to the deriver since the move here, but there has been no official release since (an issue is tracking it: #192)

I need to remove this from opam

**Comment by vch9** [comment]
We can close this I believe, it can not be installed from opam anymore.
