### ISSUE TITLE
Small list generator

### ISSUE THREAD

**Issue by copy** [c-cube/qcheck#21]
I've found that `QCheck.list` can generate relatively large list of thousands of elements, which I found to slow down my tests. It would be nice to have a generator that actually generates small lists (with, say, less than 100 elements) with a size distribution similar to `list`. The range generated by `small_signed_int`, `nat`, etc. should also be documented.

Side note: There's a minor naming inconsistency: `QCheck.list_of_size` vs `QCheck.Gen.list_size`.

**Comment by c-cube** [comment]
Yeah, the naming inconsistency is stupid. I can add `small_list` as an alias for `list_size small_nat`, what do you think?

**Comment by copy** [comment]
> Edit: should rather be list_size (0--10), same as small_string, and more reasonable

Yes, that sounds good.

**Comment by c-cube** [comment]
Fixed in ea45a6a76fa71eaba3509d4098792ea9a6378298
