### ISSUE TITLE
[Documentation] `QCheck.list` uses `Gen.nat`, not `Gen.small_nat` as suggested by documentation

### ISSUE THREAD

**Issue by just-max** [c-cube/qcheck#228]
The [documentation](https://c-cube.github.io/qcheck/0.18/qcheck-core/QCheck/#val-list) for the `list` arbitrary says the length of the resulting list is from `small_nat`. From what I can tell, the actual length is from `nat` (the arbitrary for small lists is `small_list`, where the documentation is correct).

`val list : 'a arbitrary -> 'a list arbitrary`
Generates lists with length generated by `small_nat`.

Should be

`val list : 'a arbitrary -> 'a list arbitrary`
Generates lists with length generated by `nat`.

**Comment by jmid** [comment]
Thanks for the report!
You are right - there's a fix for this one and some other ones I spotted in #229.
