### ISSUE TITLE
Char generator misses '\255'

### ISSUE THREAD

**Issue by jmid** [c-cube/qcheck#23]
Two students (Kenneth and Philip) found this one:
```
# open QCheck;;
# let t = Test.make ~count:1_000_000 char (fun c -> c <> '\255');;
val t : QCheck.Test.t = QCheck.Test.Test <abstr>
# QCheck_runner.run_tests ~verbose:true [t];;                     
law <test>: 1000000 relevant cases (1000000 total)
success (ran 1 tests)
```

The problem is line 201 in src/QCheck.ml reading:  `let char st = char_of_int (RS.int st 255)`
The last constant should be `256` as `Random.State.int` generates numbers excluding the given upper bound. If one changes the above to test for another character, e.g., `'\254'`, a counterexample is found.

**Comment by c-cube** [comment]
Ah, my bad indeed. Will fix soon.
