### ISSUE TITLE
count cannot be zero

### ISSUE THREAD

**Issue by vbgl** [c-cube/qcheck#254]
In `0.19` (since #220), the `~count` argument to `Test.make` can no longer be zero.

Why?

Is this documented?

Using a zero count can be used to disable a test. Real-life use:
https://github.com/andrenth/ocaml-stdint/blob/0.7.0/tests/stdint_test.ml#L6

**Comment by vch9** [comment]
The correct modification should forbid negative counts (and long factors). I fixed the issue in https://github.com/c-cube/qcheck/pull/255

**Comment by jmid** [comment]
This was an unintended regression. I'll try rolling out a patched 0.19.1 later today or tomorrow.

**Comment by vbgl** [comment]
That was (very) fast! Thank you all.
