### ISSUE TITLE
function to find (counter)examples inside properties

### ISSUE THREAD

**Issue by c-cube** [c-cube/qcheck#31]
Say:

```ocaml
val find_example : ?count:int -> ('a -> bool) -> 'a arbitrary -> 'a option
```

that should be used (with shrinking?) to synthesize a function inside a property. See #8 for some discussion, e.g. for devising a strategy for the Nim game.

@jmid pointed to https://vimeo.com/143848099

**Comment by c-cube** [comment]
So I'd like more input on this (how is it expected  to be used)

**Comment by jmid** [comment]
A few thoughts:
I believe we want examples with nested quantifiers, like Norell's second Nim example.
For all strategies s, numbers n. s is losing iff exists a counter-strategy s'. `play n ("1",s) ("2",s') = "2"`
I believe we want to express `is_losing` with `find_example`.

For another example with nested quantifiers where `find_example` could be useful is non-interference as in this paper from ICFP'13: http://www.seas.upenn.edu/~aarthur/testing-noninterference-draft-full.pdf
Here, I believe `find_example` could come into play to express "an adversary cannot tell two low-equivalent states apart". (A PhD student at DTU did a project on this topic for the January course. I can ask if he wants to share his code).

**Comment by c-cube** [comment]
I've been thinking a bit, I think I can easily expose such a `find_example` function, but which would return a `'a` instead of `'a option`. In case no example could be found, the whole input would be marked as "failed precondition" (or a similar non-failure condition), rather than failed. What do you think @jmid ?

**Comment by c-cube** [comment]
It seems to work:

```ocaml
# QCheck.find_example_gen QCheck.small_int ~f:(fun x->x mod 2=0);;
- : int = 58
# QCheck.find_example_gen ~count:10_000 QCheck.small_int ~f:(fun x->x =10);;
- : int = 10
```

Note that the main function should be `find_example`, which takes an `'a arbitrary` and a predicate and returns a new `'a arbitrary`.

**Comment by c-cube** [comment]
I'm not sure whether the base definition should take and return an `'a arbitrary`, or just a `'a Gen.t`. The latter is less demanding so it might be better (ask for the minimal required information).

**Comment by jmid** [comment]
Thanks for this! Do you know whether it can be used for "recursive" invocation inside a QCheck property to express properties with nested quantifiers?
I don't know a good, minimal example of such a property though. Perhaps `forall n > 1. exists m. n < m < 2n` where we would then use `find_example` to express existence?

How does `find_example` signal "I couldn't find an example" API-wise?
In Ulf Norell's Nim example, I would want to use `find_example` to express `is_winning` formulated as "`find_example` cannot find me a counterexample strategy".

**Comment by c-cube** [comment]
On failure, it raises an exception `No_example_found`. For your example, it would probably look like this (assuming a slightly modified version that returns an `'a Gen.t`) if you want to generate such a `(m,n)`:

```ocaml
let gen =
  2 -- 50 >>= fun n ->
  find_example_gen (2--100) (fun m -> n < m && m < 2 * n) >|= fun m -> (n,m)
in
(* property here *)
```

or, directly in the test:

```ocaml
Test.make (2--50)
  (fun n ->
     try ignore (find_example (2-- 2 * n)); true
     with No_example_found -> false)
```

Maybe a `exists_example` predicate would be helpful, too.

**Comment by jmid** [comment]
Nice! The optional `~count` parameter to `find_example_gen` should be convenient to express "search harder" for such inner invocations, especially for sufficiently complex properties not expressible as a custom generator (I am looking at you, `(2-- 2 * n)`).   :-)

**Comment by c-cube** [comment]
Yes indeed. I have modified the types and added a basic test (as in my previous comment), things seem to work.
