### ISSUE TITLE
Fail when no assumes pass

### ISSUE THREAD

**Issue by porglezomp** [c-cube/qcheck#55]
I was stubbing out functions, and was surprised when one of my properties started passing. I've figured out that it's simply failing the `assume` every time, and since it never fails, that counts as succeeding.

If not enough assumptions pass, that should be a test failure (or at the very least a warning), since it indicates that your property probably isn't testing the thing you think it's testing very well.

**Comment by Gbury** [comment]
I agree that warning (or raising an error) if no input passed the preconditions seems like a good idea.

That said, if really none of your generated input satisfies the `assume` preconditions, then I'd say that's probably a bug and you should either adjust the `max_gen` parameter of the test, or adapt the generating function to generate less invalid inputs...

**Comment by c-cube** [comment]
Interesting point indeed. I suppose we need at least a warning. Question:

- do we want to have a minimum *number* of successes, or a percentage?

**Comment by porglezomp** [comment]
Before I made the issue, I was checking around for how some other libraries handle this to try to gauge the techniques, and there seem to be a few approaches.

The original Haskell QuickCheck seems to have this be user-directed, and also use a statistical test to estimate the failure probability. FsCheck (at least by default) requires that 100 tests pass assumes, and it stops early at a global limit.
