### ISSUE TITLE
Blog post link broken in README

### ISSUE THREAD

**Issue by rjhilgefort** [c-cube/qcheck#57]
Getting a 404 for http://cedeela.fr/quickcheck-for-ocaml.html

**Comment by c-cube** [comment]
Is it? When I click on the link from the rendered readme it works for me… (with a recent firefox)

**Comment by rjhilgefort** [comment]
![2019-01-01 12 28 59](https://user-images.githubusercontent.com/2034823/50574966-f661d780-0dc0-11e9-897e-683d4c66f1fa.gif)

**Comment by c-cube** [comment]
Ah, it should be fixed for real now. The problem was:

- http URL (which my browser converts to https automatically, so it worked for me)
- missing http->https redirection in the web server

**Comment by c-cube** [comment]
Thanks for the multiple reports :+1:
