### ISSUE TITLE
Understanding the implementation of Gen.float

### ISSUE THREAD

**Issue by cemerick** [c-cube/qcheck#58]
I needed a `float_range` (perhaps a reasonable PR?), and came up with this:

```ocaml
  let float_range a b =
    if b < a then invalid_arg "Gen.float_range";
    let range = b -. a in
    fun st -> a +. RS.float st range
  let (--.) = float_range
```

Seems fine, and appears to work well in my use, but along the way I happened to look at the implementation of `Gen.float`:

https://github.com/c-cube/qcheck/blob/0dab657c3bf30b27592d01248f52149aaa538b2d/src/core/QCheck.ml#L117-L121

Some questions came to mind:

1. Why is this implemented in terms of `exp`, rather than just calling through to `RS.float`?
2. Why not use `RS.bool` to determine whether to negate, rather than generating floats and doing a comparison?
3. Why not use `~-.` instead of performing a multiplication?

**Comment by c-cube** [comment]
This comes from [qtest](https://github.com/vincent-hugot/qtest), it seems. It's old code, I never looked too much at float generators. I suppose it's not that easy to know what range to use, or maybe it's to have a certain shape in the distribution.

A PR for `float_range` would make sense! :+1:
