### ISSUE TITLE
Add Rely backend

### ISSUE THREAD

**Issue by bandersongit** [c-cube/qcheck#61]
I think making a [Rely](https://github.com/facebookexperimental/reason-native/tree/master/src/rely) backend for qcheck would be a useful. I've seen a few people express interest in creating one, so I thought I would reach out here.

Based on looking at the alcotest and oUnit implementations I think it should be fairly straightforward and I am happy to help with the translation.

**Comment by c-cube** [comment]
I would merge a PR that adds it :slightly_smiling_face: especially as a `qcheck-rely` package.

**Comment by c-cube** [comment]
Possible issue is that esy doesn't seem to be on opam *at all*, which makes a `qcheck-rely` package more difficult, I suppose.

**Comment by bandersongit** [comment]
> Possible issue is that esy doesn't seem to be on opam _at all_, which makes a `qcheck-rely` package more difficult, I suppose.

Definitely. I could try setting up an esy/npm workflow in a subdirectory in order to get the dependencies we need (namely rely), but it would certainly add some maintenance overhead particularly when it comes to releases

**Comment by c-cube** [comment]
if you want `qcheck-rely` (or `rely-qcheck`?) to live in this repo, I'm not opposed to having a package.json or something like that in there for this sub-library. I assume esy is able to work with a repo that mixes opam and esy files. Let me know what you think :slightly_smiling_face:

**Comment by bandersongit** [comment]
> if you want `qcheck-rely` (or `rely-qcheck`?) to live in this repo, I'm not opposed to having a package.json or something like that in there for this sub-library. I assume esy is able to work with a repo that mixes opam and esy files. Let me know what you think 🙂

I'll play with this today and see what I can come up with, thanks for the flexibility!

**Comment by bandersongit** [comment]
Released [@reason-native/qcheck-rely](https://github.com/facebookexperimental/reason-native/tree/master/src/qcheck-rely) to NPM
