### ISSUE TITLE
Gen.int_bound and Gen.int_range may fail with Invalid_argument

### ISSUE THREAD

**Issue by jmid** [c-cube/qcheck#7]
`Random.State.int` fails for any argument greater than `0x3FFFFFFF` on my 64bit machine:
```
# Random.State.int (Random.State.make_self_init ()) 0x3FFFFFFF;;
- : int = 271624853
# Random.State.int (Random.State.make_self_init ()) 0x40000000;;
Exception: Invalid_argument "Random.int".
```
Concretely this affects `Gen.int_range` and `Gen.int_bound`:
```
# open QCheck;;
# Gen.generate1 (Gen.int_bound 0x3FFFFFFF);;                            
Exception: Invalid_argument "Random.int".
# Gen.generate1 (Gen.int_bound 0x3FFFFFFE);;
- : int = 367212674
# Gen.generate1 (Gen.int_range 0 0x3FFFFFFF);;
Exception: Invalid_argument "Random.int".
# Gen.generate1 (Gen.int_range 0 0x3FFFFFFE);;
- : int = 829922949
```
One should consider stitching together the outcome of two `Random.State.int` calls as in the `pint` generator (or document the behaviour).

**Comment by c-cube** [comment]
It's way simpler to document the behavior indeed. I don't really know how to "stitch" together two results while keeping the distribution uniform (need to think more about it).

**Comment by c-cube** [comment]
It's a bit more documented now (barely)

**Comment by jmid** [comment]
Great, thanks. Sorry for the radio silence. I've been busy with the course :-)

**Comment by c-cube** [comment]
How is it going? :-)
Can I close this issue?

**Comment by jmid** [comment]
Yes, you are welcome to close it. In the long run it would be great to make these operations work for any intervals up to 'max_int' length.

The course is going well. I've just put up a copy of the material here: http://janmidtgaard.dk/quickcheck/
if you want to have a look.

**Comment by c-cube** [comment]
Thanks a lot! If you want to contribute some examples into the readme, it would be awesome! In particular I see that you use `collect`, very neat.
