### ISSUE TITLE
What's the workflow to observe/debug shrinking choices? (with proposals inside)

### ISSUE THREAD

**Issue by gasche** [c-cube/qcheck#71]
Here is my current scenario.

I am using a known-bug case to improve my shrinkers. I run the QCheck tests from the command-line, at the fixed seed that is known to run into the bug, and I look at the shrunk counter-example that is displayed. It doesn't look very minimal to me, so I tweak the shrinkers to get a better counter-example. When that works, I get a better counterexample and I iterate. When that does not work, I would like to understand why, in particular to understand the shrinking choices that were made.

So: I would like to use the QCheck API to debug shrinking. In particular, I would like to print (to stderr or a log file) every successful shrinking step (not all shrinking steps, which I can do by adding a debug print to my shrinker, but is too verbose). How can I do this with QCheck?

It looks like what I want is to pass my own `'a Test.handler` value, which observes all events, and add a debug print on the `Shrunk` event. But how can I pass my own handler using the API? As far as I can tell, there is no easy way to do this. `QCheck.Test.check_cell` accepts a handler as parameter, but there is no call to `check_cell` in my code, I am only using `QCheck_runner.run_tests_main`. This function internally calls `check_cell`, but there is no way for the user to pass a custom `handler` parameter to that call.

I started building a PR to do this, but then I noticed that, at this point in the test pipeline, the type of counterexamples is an existential variable (packed in the `Test` or `TestResult` constructor). Not only would an additional parameter to `run_tests_main` need to provide a polymorphic handler (noise and type complexity incoming), it's simply not the right place to add an event handler -- I want to do this while I still know what the type of my counterexample is.

In my code, the type information is known at the callsite of `QCheck.Test.make`. I could add an extra `?handler` parameter to this function, or I could easily turn my call into a lower-level call to `Test.make_cell` and add an extra `?handler` parameter there.

The problem is that cells do not carry handlers with the current API, cell *checkers* do. (And they, again, in the current pipeline, are called after the type parameter of the cell was forgotten.) So I thought I would add a `handler` field to the cells themselves; at checker-creation time, `check_cell` would compose the existing handlers (if any) with its own handler (if any). (The same reasoning might work for `step` and `callback`, but let's put this aside for now.)

The problem is that the handler type is defined as follows:

```ocaml
type 'a handler = string -> 'a cell -> 'a event -> unit
```

the handler gets passed the cell itself. If the handler needs access to the cell, and we decide that the cell should be able to carry handler, we have a cycle in type dependencies. It can be made to work, but it's ugly/complex, and it suggests that it is not the right design.

Why do handlers, steppers and callbacks have access to the cell itself? I don't see anything of value in the `'a cell` record that I would like to have access to in my handler (except maybe the `law` and `arbitrary` fields). In fact, the handler defined in `QCheck_runner` (which I suspect is the only one most QCheck users can use, due to the difficulty in hooking at the `check_cell` cell) exactly ignores the cell parameter.

Is there a better way to solve my need (debugging the shrinker behaviors on a specific CLI run) that I haven't thought about?

In the short term, I might try to send a PR using a dependency cycle between cells and handlers/steppers/callbacks; it's ugly and I think it's the wrong design, but it's non-invasive and backward-compatible.

In the medium term, could we consider dropping the `'a cell` parameter from handlers? (Is it reasonable for steppers and callbacks to do the same? I don't know what typical use-cases for those are.)? Should we pass nothing to replace it, or pass the law and arbitrary? Is this breakage of API something that QCheck developers are okay with?

In the long term, maybe there is a way to break the default runner, a big monolithic beast, so that this kind of flexibility can be obtained by some other approach than "let's add three more optional parameters to this function"? As a user, here is the experience I would like to have: given a specific CLI invocation of my tester, I would like to replace the call to `run_tests_main` in my program by a simple composition of calls of a lower-level API that (1) initializes various state in the same way, so that the program behavior is reproduced, (2) gives me more flexibility to operate on my tests, cells, checkers etc., and (3) gives me the opportunity to report the behavior in the same way, so that the interface doesn't change too much. In short, I'm suggesting that it would be useful to invert the control of `run_test_main`, so that I can access its easy-initialization and easy-reporting facilities, but be the one driving the logic in the middle.

**Comment by c-cube** [comment]
This is a subtle limitation of the design, it seems. Thanks for writing out your thoughts in such a detailed way.

I don't think there's a good way of conditionally attaching handlers to cells from the main runner (because of the existential type, as you pointed out). The current API has grown over years and is indeed not the most consistent or clear. I do like that we moved to having optional libraries for different backends (alcotest and ounit, namely), but there lacks something to build a test suite with finer control over which tests get handlers, statistic counters,  etc.

I think the short term solution is to be able to attach handlers to test cells directly (possibly with a global bool ref to enable them from the CLI). It's dirty but should give the basic ability of adding custom printing of events per test. A longer term solution would indeed go 
I would also be willing to discuss breaking changes to the API — rather, to the fine grained parts of the API — as long as basic tests and the `run_test_main` like functions are still there for more casual users. Since you seem quite heavily using property testing, it could also be an opportunity to rethink some of the base design assumptions (again, hypothesis-like frameworks are said to have strictly stronger shrinking, although I don't feel qualified right now to assess these claims).

**Comment by gasche** [comment]
I think I'll try to send something as a PR. (Something incremental.)

(Thanks, but let me politely deflect your barely disguised encouragement to start feeling co-responsible for the maintenance of QCheck. I have enough of those already!)

Re. hypothesis: I read some of the hypothesis blog posts, but there is a lot of discussion about how it's complex and constantly changing, and I have never seen a properly structured presentation of a few simple, key ideas, besides essentially doing the same thing as what Crowbar (or maybe rather Zest, also in the afl-fuzz space) does, in terms of generating from a data stream instead of a random state -- not in terms of using coverage information. It may be great, but it's not described very well anywhere I could find, and frankly I wouldn't worry too much about it for now. There is great experimentation and research to be done on property-testing libraries (some by following the Hypothesis footsteps), but making a solid usable QuickCheck library is already a very useful thing, and I think QCheck fills that spot just fine -- it's not perfect, but it's mostly fine.

**Comment by c-cube** [comment]
Alright, no worries. I'll accept that QCheck is mostly fine in its spot indeed, but improvements to the API would still be very welcome :)

**Comment by Gbury** [comment]
Maybe I'm missing something, but since the event handler gets passed the test cell, it has, among other things, access to the arbitrary, which provides facilities that can print the counter-example, even in the presence of the existential type (well actually, the whole point of passing the cell to the handler is so that the handler can print the values manipulated by the test).
So, from my point of view, the recommended way of doing what you want is to define a handler that uses the arbitrary to output the counter-examples to a given file (potentially in addition to calling the usual/standard handler ?).
In order to do that, I think there mainly lacks a way to override (or extend) the default handler in the runner, or am I missing something ?

**Comment by Gbury** [comment]
I'll try and submit a PR to do that sometime soon (this week).

**Comment by gasche** [comment]
I have a PR lying around that might help you do this, by introducing convenience functions to compose handlers.

**Comment by gasche** [comment]
Well my github fork seems to be experiencing an issue, but in the meantime here is the patchfile suitable for `git am` application:

```diff
From 146040fa6237247e6064d5cd8bf5329537e20878 Mon Sep 17 00:00:00 2001
From: Gabriel Scherer <gabriel.scherer@gmail.com>
Date: Sat, 20 Jul 2019 10:55:48 +0200
Subject: [PATCH] core: expose functions for composition of
 step,handler,callback

---
 src/core/QCheck.ml  | 22 +++++++++++++++++-----
 src/core/QCheck.mli |  6 ++++++
 2 files changed, 23 insertions(+), 5 deletions(-)

diff --git a/src/core/QCheck.ml b/src/core/QCheck.ml
index bfbf8ed..d682e31 100644
--- a/src/core/QCheck.ml
+++ b/src/core/QCheck.ml
@@ -1253,7 +1253,11 @@ module Test = struct
   (* Step function, called after each instance test *)
   type 'a step = string -> 'a cell -> 'a -> res -> unit
 
-  let step_nil_ _ _ _ _ = ()
+  let step_nil _ _ _ _ = ()
+  let step_seq s1 s2 = fun s cell v res ->
+    s1 s cell v res;
+    s2 s cell v res;
+    ()
 
   (* Events of a test *)
   type 'a event =
@@ -1265,7 +1269,11 @@ module Test = struct
 
   type 'a handler = string -> 'a cell -> 'a event -> unit
 
-  let handler_nil_ _ _ _ = ()
+  let handler_nil _ _ _ = ()
+  let handler_seq h1 h2 = fun s cell ev ->
+    h1 s cell ev;
+    h2 s cell ev;
+    ()
 
   (* state required by {!check} to execute *)
   type 'a state = {
@@ -1436,7 +1444,11 @@ module Test = struct
 
   type 'a callback = string -> 'a cell -> 'a TestResult.t -> unit
 
-  let callback_nil_ : _ callback = fun _ _ _ -> ()
+  let callback_nil : _ callback = fun _ _ _ -> ()
+  let callback_seq c1 c2 = fun s cell result ->
+    c1 s cell result;
+    c2 s cell result;
+    ()
 
   (* check that there are sufficiently many tests which passed, to avoid
      the case where they all passed by failed precondition *)
@@ -1465,8 +1477,8 @@ module Test = struct
     )
 
   (* main checking function *)
-  let check_cell ?(long=false) ?(call=callback_nil_)
-      ?(step=step_nil_) ?(handler=handler_nil_)
+  let check_cell ?(long=false) ?(call=callback_nil)
+      ?(step=step_nil) ?(handler=handler_nil)
       ?(rand=Random.State.make [| 0 |]) cell =
     let factor = if long then cell.long_factor else 1 in
     let target_count = factor*cell.count in
diff --git a/src/core/QCheck.mli b/src/core/QCheck.mli
index f385109..82383a5 100644
--- a/src/core/QCheck.mli
+++ b/src/core/QCheck.mli
@@ -823,14 +823,20 @@ module Test : sig
     | Shrinking of int * int * 'a
 
   type 'a handler = string -> 'a cell -> 'a event -> unit
+  val handler_nil : 'a handler
+  val handler_seq : 'a handler -> 'a handler -> 'a handler
   (** Handler executed after each event during testing of an instance. *)
 
   type 'a step = string -> 'a cell -> 'a -> res -> unit
+  val step_nil : 'a step
+  val step_seq : 'a step -> 'a step -> 'a step
   (** Callback executed after each instance of a test has been run.
       The callback is given the instance tested, and the current results
       of the test. *)
 
   type 'a callback = string -> 'a cell -> 'a TestResult.t -> unit
+  val callback_nil : 'a callback
+  val callback_seq : 'a callback -> 'a callback -> 'a callback
   (** Callback executed after each test has been run.
       [f name cell res] means test [cell], named [name], gave [res]. *)
 
-- 
2.20.1
```

**Comment by c-cube** [comment]
ping @gasche, I forgot to merge this. Is there a way you can retry to submit a PR? :slightly_smiling_face:

**Comment by Gbury** [comment]
Actually that's my bad, I kinda forgot to do this one, I'll try and do it by the end of the week.

**Comment by c-cube** [comment]
I want to release 1.0 once this is merged :grin:
