### ISSUE TITLE
List shrinkers fail to shrink singleton lists

### ISSUE THREAD

**Issue by jmid** [c-cube/qcheck#80]
Both `Shrink.list` and `Shrink.list_spine` fail to shrink a one-element list! 😮
There's a patch and more details in pull request #79

**Comment by c-cube** [comment]
should be fixed now, can you retry?

**Comment by jmid** [comment]
Sorry for the delay.
I've installed a locally patched 0.10 and 0.11 and both run fine - and fixes my problem.
Thanks for your efficient package maintenance! 😀
