### ISSUE TITLE
Add auto-derived generators

### ISSUE THREAD

**Issue by jmid** [c-cube/qcheck#87]
For some algebraic datatypes, e.g., the tree example from our introduction, it would be nice to be able to auto-derive a "boiler-plate" generator.

Jane Street's base_quickcheck has such a deriving feature: https://opensource.janestreet.com/base_quickcheck/
and Crowbar has a separate deriving extension here: https://github.com/yomimono/ppx_deriving_crowbar

**Comment by c-cube** [comment]
That's a no for me, at least in this repo. A `ppx_deriving_qcheck` or whatever could be useful, but I don't want to touch ppx, in the current day and age, with a 10 foot pole.
