### ISSUE TITLE
How create new arbitrary using other aribtrary

### ISSUE THREAD

**Issue by pytre** [c-cube/qcheck#91]
We use QCheck in a library which define a lot of parametrized types. Since `arbitrary` is a record with private members, how do you suggest to create new arbitrary over other arbitrary? For example if I have a type `'a non_empty_list` I would have `non_empty_list : 'a arbitrary -> 'a non_empty_list arbitrary`. 

Currently, we cheat using this kind of implementation : 
```ocaml
let non_empty_list a =
    let gen = QCheck.gen a 
    in QCheck.make (MyGen.non_empty_list gen)
``` 
but we loose Shrinking/printing etc.
Did i miss something? Thanks for your response (and for the work involved in QCheck).

P.

**Comment by c-cube** [comment]
`'a arbitrary` is a private record, which means you cannot directly build it (but you can access its fields).

As you noted, `val make : ­… -> 'a Gen.t -> 'a arbitrary` is provided to build new values of type `'a arbitrary`. The idea is that by forcing people to use `make`, we can add more fields to `'a arbitrary` without breaking user code. 

You can do something like:

```ocaml
let non_empty_list a =
  let gen = a.QCheck.gen in
  let shrink = a.QCheck.shrink |> Option.map myShrink.non_empty_list in
  (* … *)
  QCheck.make ?shrink … gen 
```

**Comment by pytre** [comment]
> 'a arbitrary is a private record, which means you cannot directly build it (but you can access its fields).

Make sense, thanks a lot!
