### ISSUE TITLE
`small` broken? fix or remove?

### ISSUE THREAD

**Issue by jmid** [c-cube/qcheck#94]
The definition of `arbitrary` contains a `small` entry:
```
type 'a arbitrary = private {
  gen: 'a Gen.t;
  print: ('a -> string) option; (** print values *)
  small: ('a -> int) option;  (** size of example *)
  ...
}
```
It is described under `test_cell` as 
```
kept for compatibility reasons; if provided, replaces
        the field [arbitrary.small].
        If there is no shrinking function but there is a [small]
        function, only the smallest failures will be printed.
```
https://github.com/c-cube/qcheck/blob/8db766505bb9be96da22a0ddd9b8ebb419735a84/src/core/QCheck.mli#L779

However I don't believe this is true any more.
Consider an example of lists without a shrinker:
```ocaml
# let g = make ~small:List.length ~print:(Print.list Print.int) Gen.(list small_int);;
val g : int list arbitrary =
  {gen = <fun>; print = Some <fun>; small = Some <fun>; shrink = None;
   collect = None; stats = []}
# let t = Test.make g (fun l -> List.rev l = l);;
# QCheck_runner.run_tests ~verbose:true [t];;
generated error fail pass / total     time test name
[✗]    2    0    1    1 /  100     0.0s anon_test_2

--- Failure --------------------------------------------------------------------

Test anon_test_2 failed (0 shrink steps):

[8; 2; 6; 7; 8; 87; 5; 7; 5; 2; 4; 3; 98; 6; 5; 4; 86; 2; 9; 6; 7; 79; 3; 67; 2; 1; 9; 58; 7; 2; 6; 4; 3; 1; 6; 80; 5; 6; 8; 0; 73; 0; 2; 9; 5; 2; 2; 2; 4; 94; 8; 0; 32; 7; 4; 2; 1; 14; 1]
================================================================================
failure (1 tests failed, 0 tests errored, ran 1 tests)
- : int = 1
```
As far as I can see, this stops on the first failure (second generated input out of two) thus never bringing `small` into play.
As such it seems `small` is broken (caveat: I may have understood how it is supposed to work).
If this is true, rather than fix this functionality
- that no one has reported broken (indicating that no one uses it?)
- that we keep only for backwards compatibility

this may be a welcome opportunity to remove it from QCheck.

**Comment by c-cube** [comment]
can you try with `max_fail:10`, for example? The default is `1` and so it stops at the first failure.

I do agree we should probably aim at removing that and release a 1.0 soon, anyway.

**Comment by jmid** [comment]
Thanks, @c-cube! `~max_fail:10` indeed did the trick:
```ocaml
# let g = make ~small:List.length ~print:(Print.list Print.int) Gen.(list small_int);;
# let t = Test.make ~max_fail:10 g (fun l -> List.rev l = l);;
# QCheck_runner.run_tests ~verbose:true [t];;
generated error fail pass / total     time test name
[✗]   15    0   10    5 /  100     0.0s anon_test_2

--- Failure --------------------------------------------------------------------

Test anon_test_2 failed (0 shrink steps):

[6; 0; 4]
================================================================================
failure (1 tests failed, 0 tests errored, ran 1 tests)
- : int = 1
```

Hm, I think we could improve the documentation here to help newcomers (and an old timer like me) understand this dependency between `~small` and `~max_fail`... 🤔

Realizing that `small` is working just fine, I actually lean towards keeping it now. Developing an effective shrinker for a non-trivial generator can be a big effort. A simple size measure for `small` is much less effort, but can still be valuable to report short(er) counterexamples.

**Comment by c-cube** [comment]
I think a warning when `max_fail=1` and `small <> None` could help?

**Comment by jmid** [comment]
Indeed! 👍🏻

**Comment by c-cube** [comment]
Then I shall await your PR :wink:
