### ISSUE TITLE
Question about integration with OUnit.

### ISSUE THREAD

**Issue by qcfu-bu** [c-cube/qcheck#96]
I have a question regarding the integration with ounit library. Ounit test results may carry messages for failed test cases. When converting qcheck to ounit, is it possilbe to make the qcheck error messages go into the ounit data type?

For exampe, a test for summing list of ints.
```ocaml
let test =
  QCheck_ounit.to_ounit_test
    ~verbose:true
    (QCheck.Test.make ~count:1000 ~name:"small_nat"
       QCheck.(list small_nat)
       (fun l -> (Sum.sum l) = sum l))

 let _ = perform_test (fun _ -> ()) test
```

For a faulty implementation of sum prints the message in stdout:
```
law small_nat: 2 relevant cases (2 total)
test `small_nat` failed on ≥ 1 cases: [2; 0] (after 7 shrink steps)
```

Is it possible for this test to return something like this?
```ocaml
 OUnit.RFailure (p, "law small_nat: 2 relevant cases (2 total)
test `small_nat` failed on ≥ 1 cases: [2; 0] (after 7 shrink steps)")
```

**Comment by c-cube** [comment]
Good question. I tried to look closer at the ounit API but it seems that `test_fun` is only of type `test_ctx -> unit`, without a clean way of reporting a failure?

I pushed a branch `tmp-issue-96` but am not sure if the `ounit2` results fit, I'm not that familiar with the runner API and `perform_test` disappeared.

**Comment by qcfu-bu** [comment]
The workaround that I ended up adopting was reimplementing the `to_ounit_test_cell` function such that the list of counter example carried by the failure exception is passed the ounit assertion.

```ocaml
let fail_printer s ls =
  (Printf.sprintf "Counter example for `%s` found:\n" s) ^
  List.fold_left (fun a b -> a ^ "\n" ^ b) "" ls

let to_ounit_test_cell ?(verbose=verbose()) ?(long=long_tests())
    ?(rand=random_state()) cell =
  let module T = QCheck.Test in
  let name = T.get_name cell in
  let run () =
    try
      T.check_cell_exn cell ~long ~rand
        ~call:(fun s ->
            Raw.callback
              ~verbose
              ~print_res:verbose
              ~print:Raw.print_std s);
      (true, name)
    with T.Test_fail (s, ls) ->
      (false, fail_printer s ls)
  in
  name >:: (fun () ->
      let (result, msg) = run()
      in assert_bool msg result)
````

Though this works for my purposes, I do wish there was an interface in the library that allows for this in general.

**Comment by c-cube** [comment]
Contributing back this API change would be very appreciated, and also the cleanest for you in the long term I think :-)

**Comment by qcfu-bu** [comment]
Thanks for the feedback, I'll think about the best way to approach this a bit more.
