### ISSUE TITLE
QCheck_base_runner does not check if output is a terminal

### ISSUE THREAD

**Issue by vrotaru** [c-cube/qcheck#97]
Well, at leas this is my impression. When I'm running it from within `ocamleditor` (with `~colors:false`) I see the following:

![image](https://user-images.githubusercontent.com/246236/92030890-5d8f1680-ed70-11ea-94e6-04e2b7a81a74.png)

(Ocaml 4.11.1, qcheck 0.14 installed via opam)

**Comment by c-cube** [comment]
would you please give it a try on the `wip-97` branch?

**Comment by vrotaru** [comment]
Sure. But it will have to wait till tomorrow.

**Comment by vrotaru** [comment]
Just tried and the annoying `..[2K` is gone. But the random seed is not printed. Is that expected?

**Comment by c-cube** [comment]
my bad, I just had to remove the reset code (this `..[2K` is an ansi escape sequence for clearing the line, just like ansi escape codes for changing the colors! :slightly_smiling_face: )

**Comment by vrotaru** [comment]
```diffdiff --git a/src/runner/QCheck_base_runner.ml b/src/runner/QCheck_base_runner.ml
index c74f040..59071b1 100644
--- a/src/runner/QCheck_base_runner.ml
+++ b/src/runner/QCheck_base_runner.ml
@@ -51,7 +51,8 @@ let st = ref None
 
 let set_seed_ ~colors s =
   seed := s;
-  if colors then Printf.printf "%srandom seed: %d\n%!" Color.reset_line s;
+  let reset_line = if colors then Color.reset_line else "" in
+  Printf.printf "%srandom seed: %d\n%!" reset_line s;
   let state = Random.State.make [| s |] in
   st := Some state;
   state
```

**Comment by c-cube** [comment]
I already pushed something similar :)

**Comment by vrotaru** [comment]
It is working as expected with the latest fix
