### ISSUE TITLE
Colors codes are print when ~verbose:true ~colors:false

### ISSUE THREAD

**Issue by vrotaru** [c-cube/qcheck#98]
Which is distracting when the `qcheck` is not running from a terminal

![image](https://user-images.githubusercontent.com/246236/92332731-9ab51a80-f088-11ea-9d80-08a608055c5c.png)

I have a fix in this branch [verbose-no-colors](https://github.com/vrotaru/qcheck/tree/verbose-no-colors). 
Not opening a PR because, you may prefer a different way of fixing it.

**Comment by c-cube** [comment]
is this related to https://github.com/c-cube/qcheck/issues/97 ?

**Comment by vrotaru** [comment]
yes

**Comment by vrotaru** [comment]
Just check with the master to be sure and the color codes are printed. 

Also, I've pushed the fix to my branch. Somehow I created the branch and pushed but forgot to add the modified file

**Comment by c-cube** [comment]
can you make a PR then?

**Comment by vrotaru** [comment]
Yes, I'll create a PR

**Comment by c-cube** [comment]
actually I pushed a change on master, would you mind retrying it? :slightly_smiling_face:

**Comment by vrotaru** [comment]
Sure

**Comment by vrotaru** [comment]
Thanks, it looks good now

**Comment by c-cube** [comment]
cool, will make a release soon :)
