### ISSUE TITLE
Handling of exception No_example_found

### ISSUE THREAD

**Issue by ghilesZ** [c-cube/qcheck#99]
Hi, i'm struggling to handle the exception `No_example_found`.

I'm building a generator using `QCheck.find_example` and then building a test using `Test.make` and i'm adding this test into a list of tests to be ran with `QCheck_base_runner.run_tests`.
However, when the generator fails to find an example, it raises the exception`No_example_found` which interrupts the running of the test suite as it is not caught by `QCheck_base_runner.run_tests`. Is there a way to ignore silently this failure using the current API?

Here is a minimal example that illustrates the behaviour:

````OCaml
open QCheck

let _ =
  let rs = make (find_example ~count:10 ~f:(fun _ -> false) Gen.int) in
  let t1 = Test.make rs (fun _ -> true) in
  let t2 = Test.make ~count:10 int (fun i -> i <= max_int) in
  QCheck_base_runner.run_tests ~verbose:true [t1;t2]
`````
Which runs the test t1, then fails. While what i would like is the test suite to be ran entirely, even if a generator does not manage to generate a value.

**Comment by jmid** [comment]
Stopping everything because of a `No_example_found` indeed sounds debatable.
Here's a suggestion for a work-around:

`assume` has this functionality of "checking the left-hand-side of an implication property",
e.g., for a generator with an additional condition.

You can thus achieve what you are after as:
```ocaml
open QCheck

let rs = make Gen.int
let t1 = Test.make rs (fun _ -> assume false; true)
let t2 = Test.make ~count:10 int (fun i -> i <= max_int)
QCheck_base_runner.run_tests ~verbose:true [t1;t2]
```
which also provides a reasonable output:
```
generated error fail pass / total     time test name
[✓]  300    0    0    0 /  100     0.0s anon_test_3
[✓]   10    0    0   10 /   10     0.0s anon_test_4

!!! Warning !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Warning for test anon_test_3:

WARNING: only 0.0% tests (of 100) passed precondition for "anon_test_3"

NOTE: it is likely that the precondition is too strong, or that the generator is buggy.
================================================================================
1 warning(s)
success (ran 2 tests)
- : int = 0
```
(here we could start discussing whether 0 errors, fails and passes should be considered a success... 🙂)

**Comment by ghilesZ** [comment]
Ok thanks that will do the job for now! Should i leave the issue open?

**Comment by c-cube** [comment]
Please keep the issue open, the exception should definitely be caught somewhere!

I agree that `assume` should play better, especially wrt minimization.

**Comment by c-cube** [comment]
Can y'all take a look at master? there is now a catch-all when running the generator, which directly turns the test into a failure. 

`make example-runner` should show the two tests above (one failing,  the other passing).

**Comment by ghilesZ** [comment]
@c-cube This looks better! However i'm wondering if this should be a failure or a warning, because the property being tested did not fail, its the generator who failed. Maybe there should be some extra argument to let the user decide.
 Anyway, i'm looking forward to seeing the next release :)

**Comment by c-cube** [comment]
honestly I think it's a failure and not a warning, `assume` is generally better (whereas this is an advanced feature) :)
if it fails this way it should be reasonably easy, I hope, to recognize it comes from `find_example` and catch the exception there.

**Comment by c-cube** [comment]
> (here we could start discussing whether 0 errors, fails and passes should be considered a success... slightly_smiling_face)

I noticed that too and fixed it. The status reporter would use number of runs, which in this case is 0 (it fails before producing _any_ input), so now it just uses the result of the test :)

**Comment by c-cube** [comment]
new release done!

**Comment by ghilesZ** [comment]
Thanks great!
